apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: www
    image: nginx:1.19-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  selector:
    app1: web
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app3: web
  template:
    metadata:
      labels:
        app3: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
